# Generated by Django 6.0.5 on 2026-06-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0009_remove_focussession_total_time_to_focus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
