# Generated by Django 6.0.5 on 2026-06-02 14:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0010_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focuscycle',
            name='duration',
            field=models.DurationField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=36000))]),
        ),
        migrations.AddConstraint(
            model_name='focuscycle',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', datetime.timedelta(seconds=60)), ('duration__lte', datetime.timedelta(seconds=36000))), name='focus_cycle_duration_between_1_and_600_minutes'),
        ),
    ]
