# Generated by Django 6.0.5 on 2026-06-02 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_session_follower_names(apps, schema_editor):
    SessionFollower = apps.get_model("realtime_timer", "SessionFollower")
    for follower in SessionFollower.objects.select_related("follower").filter(follower__isnull=False):
        follower.username = follower.username or follower.follower.username
        follower.user_type = "authenticated"
        follower.save(update_fields=["username", "user_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0011_alter_focuscycle_duration_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionfollower',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='focusperiod',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='focus_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionfollower',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('authenticated', 'Authenticated')], default='authenticated', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionfollower',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='sessionfollower',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_session_follower_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='sessionfollower',
            constraint=models.UniqueConstraint(condition=models.Q(('follower__isnull', False)), fields=('session', 'follower'), name='unique_authenticated_session_follower'),
        ),
        migrations.AddConstraint(
            model_name='sessionfollower',
            constraint=models.UniqueConstraint(fields=('session', 'username'), name='unique_session_follower_username'),
        ),
    ]
